services:
  - type: web
    name: twitch-chatgpt-bot
    runtime: node
    branch: main
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: OPENAI_API_KEY
        value: sk-proj-jGADzXMil1CSP2tp1VmHT3BlbkFJvF188Mx8m1h2QS07ezPk
      - key: CHANNELS
        value: MrDukkTV
      - key: GPT_MODE
        value: "CHAT"
      - key: HISTORY_LENGTH
        value: "3"
      - key: MODEL_NAME
        value: "gpt-3.5-turbo"
      - key: COMMAND_NAME
        value: "sirius"
      - key: TWITCH_USER  # https://dev.twitch.tv/console
        value: "f270xza0j3ru6quebqu4oxzrvsvcgn"
      - key: TWITCH_AUTH  # https://twitchapps.com/tmi/
        value: "oauth:nugv3x1hadkwwt12mu1j8kv152no9z"
      - key: SEND_USERNAME
        value: "true"
      - key: ENABLE_TTS
        value: "false"
      - key: ENABLE_CHANNEL_POINTS
        value: "false"
